services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - app-network
    env_file:
      - .env.build
  s3:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - app-network
    volumes:
      - s3-data:/data
    env_file:
      - .env.build
    environment:
      MINIO_ROOT_USER: ${DB_USER}
      MINIO_ROOT_PASSWORD: ${DB_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ':9001' /data
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env.build
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      # PostgreSQL 18+ expects mount at /var/lib/postgresql (data in subdir)
      - pgdata:/var/lib/postgresql
  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - .env.build
    ports:
      - '6379:6379'
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - '.env.build'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'timar@timar.com'
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 600M
    networks:
      - app-network

  # logstash:
  #   image: logstash:8.11.0 # Use the desired Logstash version
  #   container_name: logstash
  #   ports:
  #     - '5044:5044' # Example port for Beats input
  #     - '9600:9600' # Logstash monitoring API
  #   volumes:
  #     - ./build/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./build/logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   environment:
  #     LS_JAVA_OPTS: '-Xmx256m -Xms256m' # Adjust memory as needed
  #     ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200' # If connecting to Elasticsearch
  #   depends_on:
  #     - elasticsearch # If Elasticsearch is part of the same compose file
  #   networks:
  #     - app-network

  # # Example Elasticsearch service (if part of the same stack)
  # elasticsearch:
  #   image: elasticsearch:8.11.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - xpack.security.http.ssl.enabled=false
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - '9200:9200'
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   networks:
  #     - app-network

  # kibana:
  #   image: kibana:8.11.0
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - '5601:5601'
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - app-network

volumes:
  pgdata:
  pgadmin-data:
  s3-data:
  esdata:

networks:
  app-network:
    driver: bridge
