// Маппинг названий стран на русский язык
export const countryTranslations: Record<string, string> = {
  Afghanistan: 'Афганистан',
  'Åland Islands': 'Аландские острова',
  Albania: 'Албания',
  Algeria: 'Алжир',
  'American Samoa': 'Американское Самоа',
  AndorrA: 'Андорра',
  Angola: 'Ангола',
  Anguilla: 'Ангилья',
  Antarctica: 'Антарктида',
  'Antigua and Barbuda': 'Антигуа и Барбуда',
  Argentina: 'Аргентина',
  Armenia: 'Армения',
  Aruba: 'Аруба',
  Australia: 'Австралия',
  Austria: 'Австрия',
  Azerbaijan: 'Азербайджан',
  Bahamas: 'Багамские острова',
  Bahrain: 'Бахрейн',
  Bangladesh: 'Бангладеш',
  Barbados: 'Барбадос',
  Belarus: 'Беларусь',
  Belgium: 'Бельгия',
  Belize: 'Белиз',
  Benin: 'Бенин',
  Bermuda: 'Бермуды',
  Bhutan: 'Бутан',
  Bolivia: 'Боливия',
  'Bosnia and Herzegovina': 'Босния и Герцеговина',
  Botswana: 'Ботсвана',
  'Bouvet Island': 'Остров Буве',
  Brazil: 'Бразилия',
  'British Indian Ocean Territory': 'Британская территория в Индийском океане',
  'Brunei Darussalam': 'Бруней',
  Bulgaria: 'Болгария',
  'Burkina Faso': 'Буркина-Фасо',
  Burundi: 'Бурунди',
  Cambodia: 'Камбоджа',
  Cameroon: 'Камерун',
  Canada: 'Канада',
  'Cape Verde': 'Кабо-Верде',
  'Cayman Islands': 'Острова Кайман',
  'Central African Republic': 'Центральноафриканская Республика',
  Chad: 'Чад',
  Chile: 'Чили',
  China: 'Китай',
  'Christmas Island': 'Остров Рождества',
  'Cocos (Keeling) Islands': 'Кокосовые острова',
  Colombia: 'Колумбия',
  Comoros: 'Коморские острова',
  Congo: 'Конго',
  'Congo, The Democratic Republic of the': 'Демократическая Республика Конго',
  'Cook Islands': 'Острова Кука',
  'Costa Rica': 'Коста-Рика',
  "Cote D'Ivoire": "Кот-д'Ивуар",
  Croatia: 'Хорватия',
  Cuba: 'Куба',
  Cyprus: 'Кипр',
  'Czech Republic': 'Чехия',
  Denmark: 'Дания',
  Djibouti: 'Джибути',
  Dominica: 'Доминика',
  'Dominican Republic': 'Доминиканская Республика',
  Ecuador: 'Эквадор',
  Egypt: 'Египет',
  'El Salvador': 'Сальвадор',
  'Equatorial Guinea': 'Экваториальная Гвинея',
  Eritrea: 'Эритрея',
  Estonia: 'Эстония',
  Ethiopia: 'Эфиопия',
  'Falkland Islands (Malvinas)': 'Фолклендские острова',
  'Faroe Islands': 'Фарерские острова',
  Fiji: 'Фиджи',
  Finland: 'Финляндия',
  France: 'Франция',
  'French Guiana': 'Французская Гвиана',
  'French Polynesia': 'Французская Полинезия',
  'French Southern Territories': 'Французские Южные территории',
  Gabon: 'Габон',
  Gambia: 'Гамбия',
  Georgia: 'Грузия',
  Germany: 'Германия',
  Ghana: 'Гана',
  Gibraltar: 'Гибралтар',
  Greece: 'Греция',
  Greenland: 'Гренландия',
  Grenada: 'Гренада',
  Guadeloupe: 'Гваделупа',
  Guam: 'Гуам',
  Guatemala: 'Гватемала',
  Guernsey: 'Гернси',
  Guinea: 'Гвинея',
  'Guinea-Bissau': 'Гвинея-Бисау',
  Guyana: 'Гайана',
  Haiti: 'Гаити',
  'Heard Island and Mcdonald Islands': 'Остров Херд и острова Макдональд',
  'Holy See (Vatican City State)': 'Ватикан',
  Honduras: 'Гондурас',
  'Hong Kong': 'Гонконг',
  Hungary: 'Венгрия',
  Iceland: 'Исландия',
  India: 'Индия',
  Indonesia: 'Индонезия',
  'Iran, Islamic Republic Of': 'Иран',
  Iraq: 'Ирак',
  Ireland: 'Ирландия',
  'Isle of Man': 'Остров Мэн',
  Israel: 'Израиль',
  Italy: 'Италия',
  Jamaica: 'Ямайка',
  Japan: 'Япония',
  Jersey: 'Джерси',
  Jordan: 'Иордания',
  Kazakhstan: 'Казахстан',
  Kenya: 'Кения',
  Kiribati: 'Кирибати',
  "Korea, Democratic People'S Republic of": 'КНДР',
  'Korea, Republic of': 'Республика Корея',
  Kuwait: 'Кувейт',
  Kyrgyzstan: 'Кыргызстан',
  "Lao People'S Democratic Republic": 'Лаос',
  Latvia: 'Латвия',
  Lebanon: 'Ливан',
  Lesotho: 'Лесото',
  Liberia: 'Либерия',
  'Libyan Arab Jamahiriya': 'Ливия',
  Liechtenstein: 'Лихтенштейн',
  Lithuania: 'Литва',
  Luxembourg: 'Люксембург',
  Macao: 'Макао',
  'Macedonia, The Former Yugoslav Republic of': 'Северная Македония',
  Madagascar: 'Мадагаскар',
  Malawi: 'Малави',
  Malaysia: 'Малайзия',
  Maldives: 'Мальдивы',
  Mali: 'Мали',
  Malta: 'Мальта',
  'Marshall Islands': 'Маршалловы острова',
  Martinique: 'Мартиника',
  Mauritania: 'Мавритания',
  Mauritius: 'Маврикий',
  Mayotte: 'Майотта',
  Mexico: 'Мексика',
  'Micronesia, Federated States of': 'Микронезия',
  'Moldova, Republic of': 'Молдова',
  Monaco: 'Монако',
  Mongolia: 'Монголия',
  Montserrat: 'Монтсеррат',
  Morocco: 'Марокко',
  Mozambique: 'Мозамбик',
  Myanmar: 'Мьянма',
  Namibia: 'Намибия',
  Nauru: 'Науру',
  Nepal: 'Непал',
  Netherlands: 'Нидерланды',
  'Netherlands Antilles': 'Нидерландские Антильские острова',
  'New Caledonia': 'Новая Каледония',
  'New Zealand': 'Новая Зеландия',
  Nicaragua: 'Никарагуа',
  Niger: 'Нигер',
  Nigeria: 'Нигерия',
  Niue: 'Ниуэ',
  'Norfolk Island': 'Остров Норфолк',
  'Northern Mariana Islands': 'Северные Марианские острова',
  Norway: 'Норвегия',
  Oman: 'Оман',
  Pakistan: 'Пакистан',
  Palau: 'Палау',
  'Palestinian Territory, Occupied': 'Палестина',
  Panama: 'Панама',
  'Papua New Guinea': 'Папуа-Новая Гвинея',
  Paraguay: 'Парагвай',
  Peru: 'Перу',
  Philippines: 'Филиппины',
  Pitcairn: 'Острова Питкэрн',
  Poland: 'Польша',
  Portugal: 'Португалия',
  'Puerto Rico': 'Пуэрто-Рико',
  Qatar: 'Катар',
  Reunion: 'Реюньон',
  Romania: 'Румыния',
  'Russian Federation': 'Россия',
  RWANDA: 'Руанда',
  'Saint Helena': 'Остров Святой Елены',
  'Saint Kitts and Nevis': 'Сент-Китс и Невис',
  'Saint Lucia': 'Сент-Люсия',
  'Saint Pierre and Miquelon': 'Сен-Пьер и Микелон',
  'Saint Vincent and the Grenadines': 'Сент-Винсент и Гренадины',
  Samoa: 'Самоа',
  'San Marino': 'Сан-Марино',
  'Sao Tome and Principe': 'Сан-Томе и Принсипи',
  'Saudi Arabia': 'Саудовская Аравия',
  Senegal: 'Сенегал',
  'Serbia and Montenegro': 'Сербия и Черногория',
  Seychelles: 'Сейшелы',
  'Sierra Leone': 'Сьерра-Леоне',
  Singapore: 'Сингапур',
  Slovakia: 'Словакия',
  Slovenia: 'Словения',
  'Solomon Islands': 'Соломоновы острова',
  Somalia: 'Сомали',
  'South Africa': 'ЮАР',
  'South Georgia and the South Sandwich Islands':
    'Южная Георгия и Южные Сандвичевы острова',
  Spain: 'Испания',
  'Sri Lanka': 'Шри-Ланка',
  Sudan: 'Судан',
  Suriname: 'Суринам',
  'Svalbard and Jan Mayen': 'Шпицберген и Ян-Майен',
  Swaziland: 'Эсватини',
  Sweden: 'Швеция',
  Switzerland: 'Швейцария',
  'Syrian Arab Republic': 'Сирия',
  'Taiwan, Province of China': 'Тайвань',
  Tajikistan: 'Таджикистан',
  'Tanzania, United Republic of': 'Танзания',
  Thailand: 'Таиланд',
  'Timor-Leste': 'Восточный Тимор',
  Togo: 'Того',
  Tokelau: 'Токелау',
  Tonga: 'Тонга',
  'Trinidad and Tobago': 'Тринидад и Тобаго',
  Tunisia: 'Тунис',
  Turkey: 'Турция',
  Turkmenistan: 'Туркменистан',
  'Turks and Caicos Islands': 'Острова Теркс и Кайкос',
  Tuvalu: 'Тувалу',
  Uganda: 'Уганда',
  Ukraine: 'Украина',
  'United Arab Emirates': 'ОАЭ',
  'United Kingdom': 'Великобритания',
  'United States': 'США',
  'United States Minor Outlying Islands': 'Малые отдаленные острова США',
  Uruguay: 'Уругвай',
  Uzbekistan: 'Узбекистан',
  Vanuatu: 'Вануату',
  Venezuela: 'Венесуэла',
  'Viet Nam': 'Вьетнам',
  'Virgin Islands, British': 'Британские Виргинские острова',
  'Virgin Islands, U.S.': 'Виргинские острова США',
  'Wallis and Futuna': 'Уоллис и Футуна',
  'Western Sahara': 'Западная Сахара',
  Yemen: 'Йемен',
  Zambia: 'Замбия',
  Zimbabwe: 'Зимбабве',
};

export const countries = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];
